### ISSUE TITLE
RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.

### ISSUE THREAD

**Issue by group-up-hong** [pytorch/rfcs#55]
----------------------- --------------------
absl-py                 1.4.0
backcall                0.2.0
cachetools              5.3.0
certifi                 2023.5.7
charset-normalizer      3.1.0
colorama                0.4.6
cycler                  0.11.0
decorator               5.1.1
fonttools               4.38.0
gitdb                   4.0.10
GitPython               3.1.31
google-auth             2.17.3
google-auth-oauthlib    0.4.6
grpcio                  1.54.0
idna                    3.4
importlib-metadata      6.6.0
intel-openmp            2023.1.0
ipython                 7.34.0
jedi                    0.18.2
kiwisolver              1.4.4
Markdown                3.4.3
MarkupSafe              2.1.2
matplotlib              3.5.3
matplotlib-inline       0.1.6
numpy                   1.21.6
oauthlib                3.2.2
opencv-python           4.7.0.72
packaging               23.1
pandas                  1.3.5
parso                   0.8.3
pickleshare             0.7.5
Pillow                  9.5.0
pip                     23.1.2
prompt-toolkit          3.0.38
protobuf                3.20.3
psutil                  5.9.5
pyasn1                  0.5.0
pyasn1-modules          0.3.0
Pygments                2.15.1
pyparsing               3.0.9
python-dateutil         2.8.2
pytz                    2023.3
PyYAML                  6.0
requests                2.30.0
requests-oauthlib       1.3.1
rsa                     4.9
scipy                   1.7.3
seaborn                 0.12.2
setuptools              67.8.0
six                     1.16.0
smmap                   5.0.0
tensorboard             2.11.2
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
thop                    0.1.1.post2209072238
torch                   1.9.0+cu111
torchaudio              0.9.0
torchvision             0.10.0+cu111
tqdm                    4.65.0
traitlets               5.9.0
typing_extensions       4.5.0
urllib3                 2.0.2
wcwidth                 0.2.6
Werkzeug                2.2.3
wheel                   0.40.0
zipp                    3.15.0

Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       0/99         0G    0.08128     0.0397    0.04652          2        640: 100%|██████████| 443/443 [16:01<00:00,  2.17s/it]
                 Class     Images  Instances          P          R      mAP50   mAP50-95:   0%|          | 0/4 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "D:\code\yolov5-master\train.py", line 642, in <module>
    main(opt)
  File "D:\code\yolov5-master\train.py", line 531, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:\code\yolov5-master\train.py", line 364, in train
    compute_loss=compute_loss)
  File "C:\Users\czh\anaconda3\envs\yolo666\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "D:\code\yolov5-master\val.py", line 219, in run
    loss += compute_loss(train_out_clone, targets)[1]
  File "D:\code\yolov5-master\utils\loss.py", line 163, in __call__
    obji = self.BCEobj(pi[..., 4], tobj)
  File "C:\Users\czh\anaconda3\envs\yolo666\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\czh\anaconda3\envs\yolo666\lib\site-packages\torch\nn\modules\loss.py", line 716, in forward
    reduction=self.reduction)
  File "C:\Users\czh\anaconda3\envs\yolo666\lib\site-packages\torch\nn\functional.py", line 2960, in binary_cross_entropy_with_logits
    return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)
RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.

How can I resolve the error mentioned above?

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/
